# Site settings
title: Thando Mantsha
email: me@thandomantsha.com
description: > # this means to ignore newlines until "baseurl:"
  This is the online home of Thando Mantsha. Find my contact details and enjoy my ramblings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thandomantsha.com" # the base hostname & protocol for your site
twitter_username: thandomantsha
github_username:  thandomantsha

# Build settings
markdown: kramdown
